#!/usr/bin/env node
/* build.mjs — splice games/hexis/src/*.js into hexis.html.
 *
 * The 2.x file was authored as one document with `/* ===== NN-name.js ===== *​/`
 * banners marking where a split source would have been. 3.0 keeps the sources
 * as real files and writes them back into the single-file build, so the thing
 * you ship is still one HTML file you can double-click, and the thing you edit
 * is still a directory of modules.
 *
 * Idempotent: everything between the two markers is replaced on every run, so
 * building twice produces the same file.
 *
 *   node build.mjs            rebuild hexis.html from src/
 *   node build.mjs --check    parse-check only, write nothing
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const HTML = join(here, 'hexis.html');
const SRC = join(here, 'src');

const OPEN = '/* >>> HEXIS 3.0 — generated by build.mjs from src/, do not edit below >>> */';
const CLOSE = '/* <<< end HEXIS 3.0 modules <<< */';

const checkOnly = process.argv.includes('--check');

const files = readdirSync(SRC).filter(f => f.endsWith('.js')).sort();
if (!files.length) {
  console.error('build: no modules in src/');
  process.exit(1);
}

const body = files.map(f => readFileSync(join(SRC, f), 'utf8').replace(/\s*$/, '')).join('\n\n');
const block = OPEN + '\n\n' + body + '\n\n' + CLOSE + '\n';

let html = readFileSync(HTML, 'utf8');

const openAt = html.indexOf(OPEN);
if (openAt >= 0) {
  const closeAt = html.indexOf(CLOSE, openAt);
  if (closeAt < 0) { console.error('build: found the open marker with no close marker'); process.exit(1); }
  html = html.slice(0, openAt) + block + html.slice(closeAt + CLOSE.length + 1);
} else {
  // First run: insert immediately before the closing script tag.
  const tag = html.lastIndexOf('</script>');
  if (tag < 0) { console.error('build: no </script> in hexis.html'); process.exit(1); }
  html = html.slice(0, tag) + '\n' + block + html.slice(tag);
}

// Keep the build stamp on the title screen honest. Bump this, not the HTML.
const VERSION = '3.8 · Stormbreak';
html = html
  .replace(/Hexis \d+\.\d+(\.\d+)? · (The Storm Trilogy|Stormbreak)/g, 'Hexis ' + VERSION)
  .replace(/<div class="build">[^<]*<\/div>/, '<div class="build">Hexis ' + VERSION + '</div>');

if (checkOnly) {
  console.log('build --check: ' + files.length + ' modules, ' +
    (block.length / 1024).toFixed(0) + ' KB, would write ' + (html.length / 1024).toFixed(0) + ' KB');
  process.exit(0);
}

writeFileSync(HTML, html);
console.log('build: ' + files.length + ' modules -> hexis.html  (' +
  (html.length / 1024).toFixed(0) + ' KB total, ' + (block.length / 1024).toFixed(0) + ' KB new)');
for (const f of files) console.log('   · ' + f);
